Drill4J/test2code-ui

- src/common/get-modal-path.ts
- src/components/tests-to-run-url/admin-url.ts
- src/components/tests-to-run-url/get-tests-to-run-url.ts
- src/components/tests-to-run-url/index.ts
- src/components/tests-to-run-url/tests-to-run-url.tsx
- src/hooks/use-previouse-build-coverage.ts
- src/modules/index.ts
- src/pages/agent/agent.tsx
- src/pages/agent/build-overview/coverage-plugin-header/coverage-plugin-header.tsx
- src/pages/agent/tests-to-run/bar-chart/bar-chart.tsx
- src/pages/agent/tests-to-run/bar-chart/chart.tsx
- src/pages/agent/tests-to-run/bar-chart/index.ts
- src/pages/agent/tests-to-run/index.ts
- src/pages/agent/tests-to-run/tests-to-run-header/get-suggested-tests-modal/get-suggested-tests-modal.tsx
- src/pages/agent/tests-to-run/tests-to-run-header/get-suggested-tests-modal/index.ts
- src/pages/agent/tests-to-run/tests-to-run-header/index.ts
- src/pages/agent/tests-to-run/tests-to-run-header/saved-time-section/index.ts
- src/pages/agent/tests-to-run/tests-to-run-header/saved-time-section/saved-time-section.tsx
- src/pages/agent/tests-to-run/tests-to-run-header/tests-to-run-header.tsx
- src/pages/agent/tests-to-run/tests-to-run.tsx
> EPMDJ-7868: Implement tests-to-run page

- src/modules/active-scope-info/active-scope-info.tsx
- src/pages/agent/api/toggle-scope.ts
- src/pages/agent/scope-overview/scope-overview-header/scope-overview-header.tsx
> EPMDJ-7875: Add active session indicator

- src/Drill4J-test-to-code.tsx
- src/hooks/use-agent-route-params.ts
- src/hooks/use-build-version.ts
- src/hooks/use-group-route-params.ts
- src/hud/agent-hud.tsx
- src/hud/service-group-hud.tsx
- src/pages/agent/all-scopes/all-scopes.tsx
- src/router/index.ts
> EPMDJ-7876: Dashboard not load data fix

- src/modules/associated-test-modal/associated-test-modal.tsx
- src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
- src/modules/quality-gate-pane/quality-gate-pane.tsx
- src/pages/agent/baseline-build-modal/baseline-build-modal.tsx
> EPMDJ-7962: modals and panels not load params from url

- package-lock.json
- package.json
- src/modules/quality-gate-pane/quality-gate-pane.tsx
- src/modules/quality-gate-pane/quality-gate-settings/quality-gate-settings.tsx
- src/modules/quality-gate-pane/quality-gate-settings/threshold-value-field/threshold-value-field.tsx
- src/modules/quality-gate-pane/quality-gate-status/condition/condition.tsx
- src/modules/quality-gate-pane/quality-gate-status/quality-gate-status.tsx
> EPMDJ-7977: Quality gate improves

- package.json
- src/Drill4J-test-to-code.tsx
> EPMDJ-8129: Export t2c routes for admin-app

- package.json
- src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
- src/modules/sessions-management-pane/sessions-management-pane.tsx
> EPMDJ-8183: Update checkbox color and opening the start page after start new session

- src/pages/agent/scope-modals/finish-scope-modal/finish-scope-modal.tsx
> EPMDJ-8182: Checkbox label is not displayed in finish scope modal

- package.json
- src/pages/agent/build-overview/build-tests-info/build-tests-info.tsx
- src/pages/agent/scope-overview/scope-tests-info/scope-tests-info.tsx
> EPMDJ-8204: Add search for tests tables

- package.json
- src/pages/group/finish-all-scopes-modal/finish-all-scopes-modal.tsx
> EPMDJ-8209: Fix empty page after opened session management pane

- package.json
- src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
- src/pages/agent/agent.tsx
- src/pages/agent/build-overview/coverage-plugin-header/coverage-plugin-header.tsx
> EPMDJ-8183: Change opacity of text if checkbox is disabled

- package.json
- src/pages/agent/scope-modals/finish-scope-modal/finish-scope-modal.tsx
> EPMDJ-8215: Fix the empty page after finish scope without  coverage

- package.json
- src/pages/agent/tests-table/test-details.tsx
- src/pages/agent/tests-to-run/tests-to-run-header/tests-to-run-header.tsx
- src/pages/agent/tests-to-run/tests-to-run.tsx
- src/types/test-coverage-info.ts
> EPMDJ-8221: Support DTO changes

- .gitignore
- package.json
- src/Drill4J-test-to-code.tsx
- src/components/tests-to-run-modal/tests-to-run-modal.tsx
- src/components/tests-to-run-url/admin-url.ts
- src/hud/agent-sections/coverage-section.tsx
- src/index.css
- src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx
- src/modules/quality-gate-pane/quality-gate-status/quality-gate-status.tsx
- src/pages/agent/all-scopes/all-scopes.tsx
- src/pages/agent/baseline-build-modal/baseline-build-modal.tsx
- src/pages/agent/tests-to-run/tests-to-run-header/get-suggested-tests-modal/get-suggested-tests-modal.tsx
- src/tailwind.css
> EPMDJ-8137: Layout fixes

- package.json
- src/modules/quality-gate-pane/quality-gate-status/admin-url.ts
> EPMDJ-8137: Fix incorrect protocol in quality gate pane

- package.json
- src/hud/agent-sections/coverage-section.tsx
> EPMDJ-8219: Fix incorrect plugin link on dashboard page

- package-lock.json
- package.json
- src/pages/group/group.tsx
> EPMDJ-7867: Fix open t2c page instead of builds from SG page

- package.json
- src/pages/agent/scope-overview/scope-overview.tsx
> EPMDJ-8274: Remove the double line under the test/methods tables

- package-lock.json
- package.json
- src/Drill4J-test-to-code.tsx
> EPMDJ-8279: Add log plugin version

- package-lock.json
- package.json
- src/modules/quality-gate-pane/quality-gate-pane.tsx
- src/modules/quality-gate-pane/quality-gate-settings/quality-gate-settings.tsx
- src/modules/quality-gate-pane/quality-gate-settings/threshold-value-field/threshold-value-field.tsx
- src/modules/sessions-management-pane/management-active-sessions/management-active-sessions.tsx
- src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
- src/modules/sessions-management-pane/sessions-management-pane.tsx
- src/pages/agent/scope-modals/rename-scope-modal/rename-scope-modal.tsx
- webpack.config.js
> EPMDJ-8287: Support sharing ui kit

- package-lock.json
- package.json
- src/pages/agent/methods-table/methods-table.tsx
> EPMDJ-8407: Fix table paddings

- package.json
- src/pages/agent/build-overview/build-methods-info/active-build-coverage-info/active-build-coverage-info.tsx
- src/pages/agent/build-overview/build-methods-info/active-build-coverage-info/multi-progress-bar/multi-progress-bar.tsx
- src/pages/agent/build-overview/build-methods-info/build-methods-info.tsx
> EPMDJ-8455: Add progress bar animation

- package.json
- src/hud/agent-sections/coverage-section.tsx
- src/pages/agent/build-overview/coverage-plugin-header/coverage-plugin-header.tsx
- src/pages/agent/methods-table/methods-table.tsx
- src/pages/agent/tests-table/test-details.tsx
- src/pages/agent/tests-to-run/tests-to-run.tsx
> EPMDJ-8390: Add ellipsis for tables

- package.json
- src/pages/agent/build-overview/build-methods-info/active-build-coverage-info/active-build-coverage-info.tsx
- src/pages/agent/build-overview/build-methods-info/active-build-coverage-info/multi-progress-bar/multi-progress-bar.tsx
> EPMDJ-8479: Refactor multi-progress-bar props
